name: CI

on:
  - push
  - pull_request 

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # See https://github.com/pulsar-edit/pulsar/pull/46 for why we set this env variable.
  
jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-2019]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the Latest Package Code
        uses: actions/checkout@v3
      - name: Setup Pulsar Editor 
        uses: pulsar-edit/action-pulsar-dependency@2.1
        with:
          package-to-test: "github"
      - name: Run the headless Pulsar Tests
        uses: GabrielBB/xvfb-action@v1
        with:
          run: yarn start --test spec
          working-directory: ./pulsar
